name: Production Deployment

on:
  push:
    branches:
      - production

jobs:
  get-pr-info:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.get-merged-pr.outputs.number }}
      slot_name: ${{ steps.get-merged-pr.outputs.slot_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR number from merge commit
        id: get-merged-pr
        uses: actions/github-script@v7
        with:
          script: |
            const commit = context.sha;
            const { data: commits } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commit
            });

            if (commits.length === 0) {
              core.setFailed('No PR found associated with this merge commit');
              return;
            }

            const prNumber = commits[0].number;
            core.setOutput('number', prNumber);
            core.setOutput('slot_name', `pr-${prNumber}`);
            console.log(`Found PR #${prNumber} associated with merge commit ${commit}`);

  wait-for-approval:
    needs: get-pr-info
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://educareintertechnology-${{ needs.get-pr-info.outputs.slot_name }}.azurewebsites.net
    steps:
      - name: Approval gate
        run: echo "Waiting for approval to swap slot ${{ needs.get-pr-info.outputs.slot_name }} to production..."

  swap-to-production:
    needs: [get-pr-info, wait-for-approval]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Swap Slots
        run: |
          az webapp deployment slot swap \
            --name educareintertechnology \
            --resource-group rg-deployment-educare \
            --slot ${{ needs.get-pr-info.outputs.slot_name }} \
            --target-slot production

      - name: Verify Slot Swap
        run: |
          echo "Waiting for deployment to stabilize..."
          sleep 30

          echo "Verifying production deployment..."
          CURRENT_IMAGE=$(az webapp config container show \
            --name educareintertechnology \
            --resource-group rg-deployment-educare \
            --query "[?name=='DOCKER_CUSTOM_IMAGE_NAME'].value | [0]" \
            --output tsv)

          echo "Current production image: $CURRENT_IMAGE"

          # Extract just the PR number from image tag
          CURRENT_PR=$(echo "$CURRENT_IMAGE" | grep -oP 'pr-\d+')
          EXPECTED_PR="${{ needs.get-pr-info.outputs.pr_number }}"

          echo "Current PR: $CURRENT_PR"
          echo "Expected PR: $EXPECTED_PR"

          # Simple numeric comparison
          if [ "$CURRENT_PR" != "$EXPECTED_PR" ]; then
            echo "❌ Production does not have the correct image!"
            echo "Expected PR: $EXPECTED_PR"
            echo "Found PR: $CURRENT_PR"
            exit 1
          fi

          echo "✅ Production deployment verification completed successfully!"

      - name: Delete PR Slot
        if: success()
        run: |
          az webapp deployment slot delete \
            --name educareintertechnology \
            --resource-group rg-deployment-educare \
            --slot ${{ needs.get-pr-info.outputs.slot_name }}
