name: Deploy to Azure Web App

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - "production"

permissions:
  actions: read
  contents: read
  checks: read # Add this permission

jobs:
  deploy:
    name: Deploy to Azure
    environment:
      name: production
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.head_branch == 'production' &&
      github.event.workflow_run.workflow_id != github.workflow

    steps:
      - name: Detailed Workflow Debug
        run: |
          echo "Workflow details:"
          echo "Trigger workflow ID: ${{ github.event.workflow_run.workflow_id }}"
          echo "Current workflow ID: ${{ github.workflow }}"
          echo "Event workflow name: ${{ github.event.workflow_run.name }}"
          echo "Event type: ${{ github.event.workflow_run.event }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Status: ${{ github.event.workflow_run.status }}"

      - name: Debug Trigger Info
        run: |
          echo "Triggering workflow: ${{ github.event.workflow_run.name }}"
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Event: ${{ github.event_name }}"

      - name: Enhanced Debug Info
        run: |
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow Name: ${{ github.event.workflow_run.name }}"
          echo "Workflow Status: ${{ github.event.workflow_run.status }}"
          echo "Workflow Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"

      - name: Branch Debug Info
        run: |
          echo "Current branch: ${{ github.ref }}"
          echo "Default branch: ${{ github.event.repository.default_branch }}"
          echo "Source workflow branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Workflow source: ${{ github.event.workflow_run.path }}"

      # Get the latest version tag
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "DEPLOY_VERSION=$latest_tag" >> $GITHUB_ENV

      # Login to Azure with improved error handling getting from secrets
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          clientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
        continue-on-error: false

      - name: Verify Azure Connection
        run: |
          echo "Verifying Azure connection..."
          az account show
          if [ $? -ne 0 ]; then
            echo "Failed to verify Azure connection"
            exit 1
          fi

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: "educare-webapp" # Replace with your web app name
          slot-name: "educareintertechnology-pre-deployment" # Replace with your slot name
          images: "educare.azurecr.io/educare-deployment:${{ env.DEPLOY_VERSION }}" # latest version will be picked up

      - name: Deployment Status
        if: always()
        run: |
          if [ "${{ steps.deploy.outcome }}" == "success" ]; then
            echo "✅ Deployment successful"
          else
            echo "❌ Deployment failed"
            exit 1
          fi
