name: Deploy to Azure Web App

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"] # This must match EXACTLY
    types:
      - completed
    branches:
      - "production"

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    name: Deploy to Azure
    environment:
      name: production
    #   url: ${{ steps.deploy.outputs.webapp-url }}
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.head_branch == 'production'

    steps:
      # Add debugging step
      - name: Debug Trigger Info
        run: |
          echo "Triggering workflow: ${{ github.event.workflow_run.name }}"
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Event: ${{ github.event_name }}"

      - name: Enhanced Debug Info
        run: |
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow Name: ${{ github.event.workflow_run.name }}"
          echo "Workflow Status: ${{ github.event.workflow_run.status }}"
          echo "Workflow Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"

      # Get the latest version tag
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "DEPLOY_VERSION=$latest_tag" >> $GITHUB_ENV

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: "educare-webapp" # Replace with your web app name
          slot-name: "educareintertechnology-pre-deployment" # Replace with your slot name
          images: "educare.azurecr.io/educare-deployment:${{ env.DEPLOY_VERSION }}" # latest version will be picked up
